# Site settings
title: DS_Store
description: 'Business Card Page'
url: '#'
baseurl: ''
profilepic: '/images/icon-solar.svg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'DS_Store'
  email: standardsolargj@gmail.com
  twitter_username: standardsoalr
#  facebook_username: joshgerdes
  github_username:  standardsolar
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
